#ifndef SPECTRAL_PARAM_DEFAULTS_H
#define SPECTRAL_PARAM_DEFAULTS_H

#include"define_spectral_codes.h"

#define N_GENERATIONS_DEFAULT 10
#define N_PRINT_DEFAULT 100
#define PERTURBATION_GEN_DEFAULT 5
#define ASYMMETRY_DEFAULT 0
#define PERTURBATION_FRACTION_DEFAULT 0
#define CUTOFF_POINT_DEFAULT 0
#define SEED_RADIUS_DEFAULT 1.0
#define SEED_LENGTH_DEFAULT 6.0
#define SCALE_FACTOR_DEFAULT 3.0

#endif