#ifndef SPECTRAL_OPTION_DEFAULTS_H
#define SPECTRAL_OPTION_DEFAULTS_H

#include"define_spectral_codes.h"

#define TREE_DEFAULT MODEL_FROM_FILE
#define EDGE_WEIGHT_DEFAULT RESISTANCE_WEIGHTING
#define OPERATOR_DEFAULT MAURY
#define ORDER_DEFAULT LARGEST_MODES
#define CUTOFF_MODE_DEFAULT NO_CUTOFF
#define OUTPUT_SORT_DEFAULT PRINT_LARGEST_MODES
#define PRINT_VTK_DEFAULT true
#define PRINT_CSV_DEFAULT true

#endif